### ISSUE TITLE
HTML/CSS for index page 

### ISSUE THREAD

**Issue by KonstantinKudelko** [ke-community/platform#15]

**Comment by KonstantinKudelko** [comment]
Design:
https://www.figma.com/file/KMGUmQO7Lt0yi6LEruUwjX/Ke.landing

**Comment by mahimagoyalx** [comment]
Can I work on this issue?

**Comment by KonstantinKudelko** [comment]
> Can I work on this issue?

This task is already done, but you can try to get another one)
