### ISSUE TITLE
Automatically prerender every page (article)

### ISSUE THREAD

**Issue by artalar** [ke-community/platform#4]
Next.js and the client code already has it functionality - we need a webhook to articles creation and editing for updates static generated pages.

UPD: frontend already includes all necessary code for dynamic prerender, all we need is a webhook

**Comment by KonstantinKudelko** [comment]
@artalar can you describe more about this issue? I just don't understand the problem, sorry)

**Comment by artalar** [comment]
@KonstantinKudelko here a detailed doc: https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration
We already use it in as `unstable` future, now we need to upgrade `next.js` to **9.5** and remove `unstable_` from options.

**Comment by KonstantinKudelko** [comment]
Updated:

https://github.com/ke-community/platform/commit/f9efab0f5bba02527033980090abaffcdedb8e94
